import os

Import("env")

env_dir = env.subst("$PROJECT_DIR")
dotenv_path = os.path.join(env_dir, ".env")
cred_path = os.path.join(env_dir, "include", "credentials.h")

lines = [
    "// Auto-generated by load_env.py — do not edit",
    "// Create/edit .env instead, then rebuild",
    "#pragma once",
]

if os.path.exists(dotenv_path):
    with open(dotenv_path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip().strip("\"'")
            if key and value:
                lines.append(f"#ifndef {key}")
                lines.append(f'#define {key} "{value}"')
                lines.append("#endif")
                print(f"  load_env: {key}=...")
    print("  load_env: done")
else:
    lines.append("#error .env not found — copy .env.sample to .env and fill credentials")
    print("  load_env: .env not found; credentials.h will cause #error")

os.makedirs(os.path.dirname(cred_path), exist_ok=True)
with open(cred_path, "w") as out:
    out.write("\n".join(lines) + "\n")
print(f"  -> {cred_path}")
